// Angular_React_Vue/Day16/Assignments/Vue/Source/access-control/src/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid px-3 fs-5">
        <ul class="navbar-nav">
          <li class="nav-item">
            <router-link to="/" class="nav-link text-white">Login</router-link>
          </li>
          <li class="nav-item">
            <router-link to="/Admin" class="nav-link text-white"
              >Admin</router-link
            >
          </li>
          <li class="nav-item">
            <router-link to="/User" class="nav-link text-white"
              >User</router-link
            >
          </li>
        </ul>
      </div>
    </nav>
    <div>
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style></style>

// Angular_React_Vue/Day14/Practice/React/Source/react-routing/src/App.js
import './App.css';
import { NavLink, Outlet } from "react-router-dom";


function App() {
    return (
        <div>
            <nav className="navbar navbar-expand-sm bg-dark navbar-dark">
                <div className="container-fluid">
                <ul className="navbar-nav">
                    <li className="nav-item">
                        <NavLink to="/invoices" className={({ isActive }) => isActive ? "text-primary nav-link" : "nav-link"}>Invoices</NavLink>
                    </li>
                    <li className="nav-item">
                        <NavLink to="/expenses" className={({ isActive }) => isActive ? "text-primary nav-link" : "nav-link"}>Expenses</NavLink>
                    </li>
                </ul>
                </div>
            </nav>
            <div>
                <Outlet />
            </div>
        </div>
    );
}

export default App;
