// Angular_React_Vue/Day6/Assignments/Angular/Source/product-display/src/app/product-list/product-list.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  @Input() ProductList: {"ProductName": string, "Price": number, "Qty": number, "Amount": number, "PayableAmount": number}[] = [];

}

<div class="container mx-auto my-2">
    <table class="table my-3 table-striped">
        <caption></caption>
        <thead>
            <tr>
               <th>Product Name</th> 
               <th>Price</th>
               <th>Quantity</th>
               <th>Amount</th>
               <th>Payable Amount</th>
            </tr>
        </thead>
        <tbody class="text-primary">
            <tr *ngFor="let product of ProductList">
                <td>{{ product.ProductName }}</td>
                <td>{{ product.Price }}</td>
                <td>{{ product.Qty }}</td>
                <td>{{ product.Amount }}</td>
                <td>{{ product.PayableAmount }}</td>
            </tr>
        </tbody>
    </table>
</div>

// Vue/Day 6/Assignments/Products/Source/product-display/src/components/ProductListComponent.vue
<template lang="en">
    <div>
       <div class="container mx-auto my-2">
            <table class="table my-3 table-striped">
                <caption></caption>
                <thead>
                    <tr>
                    <th>Product Name</th> 
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                    <th>Payable Amount</th>
                    </tr>
                </thead>
                <tbody class="text-primary">
                    <tr v-for="(product, index) in ProductList" :key="index">
                        <td>{{ product.ProductName }}</td>
                        <td>{{ product.Price }}</td>
                        <td>{{ product.Qty }}</td>
                        <td>{{ product.Amount }}</td>
                        <td>{{ product.PayableAmount }}</td>
                    </tr>
                </tbody>
            </table>
        </div> 
    </div>
</template>
<script>
export default {
    name: 'ProductListComponent',
    props: {
        ProductList: Array
    }
}
</script>
<style scoped></style>
