// Angular_React_Vue/Day1/Practice/Angular/Source/componentDemo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'componentDemo';
  name: string = "Charmi Jadawala";
}

<div class="container">
    <h3 class="display-6 text-center text-secondary">Hello World</h3>

    <header>
      <h2 class="display-5 text-center text-danger">Greeting of the Day !!!</h2>
      <h1 class="display-4 text-center text-primary">Welcome {{ name }}</h1>
    </header>

    <form action="" class="ms-0 m-4 text-danger">
      <label for="fname" class="form-label fs-5">Enter your Name: </label>
      <input type="text" class="form-control-sm mx-2 text-success" name="fname" id="fname" value="{{ name }}"/>
    </form>

    <app-hello-world></app-hello-world>
</div>

// React/Day 1/Practice/Components/Source/component-demo/src/App.js
import './App.css';
import MyComponent from './HelloWorld';

var name = "Charmi Jadawala";

function App() {
  return (
    <div>
        <div className="App">
            <h3>Hello World</h3>

            <header>
                <h2>Greeting of the Day !!!</h2>
                <h1>Welcome { name }</h1>
            </header>

            <form action="">
                <label for="fname">Enter your Name: </label>
                <input type="text" name="fname" id="fname" />
            </form>  
        </div>
        <div className="MyComponent">
            <MyComponent></MyComponent>
        </div>
    </div>
  );
}

export default App;
