// Angular_React_Vue/Day16/Practice/React/Source/authguard/src/App.js
import "./App.css";
import { NavLink, Outlet } from 'react-router-dom';

function App() {
  return (
    <div>
      <nav className="navbar navbar-expand-sm bg-dark navbar-dark">
        <div className="container-fluid">
          <ul className="navbar-nav">
            <li className="nav-item">
              <NavLink
                to="/"
                className={({ isActive }) =>
                  isActive ? "text-primary nav-link" : "nav-link"
                }
              >
                Home
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/about"
                className={({ isActive }) =>
                  isActive ? "text-primary nav-link" : "nav-link"
                }
              >
                About
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/login"
                className={({ isActive }) =>
                  isActive ? "text-primary nav-link" : "nav-link"
                }
              >
                Login
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/protected"
                className={({ isActive }) =>
                  isActive ? "text-primary nav-link" : "nav-link"
                }
              >
                Protected
              </NavLink>
            </li>
          </ul>
        </div>
      </nav>
      <div>
        <Outlet />
      </div>
    </div>
  );
}

export default App;

// Angular_React_Vue/Day16/Assignments/Vue/Source/access-control/src/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid px-3 fs-5">
        <ul class="navbar-nav">
          <li class="nav-item">
            <router-link to="/" class="nav-link text-white">Login</router-link>
          </li>
          <li class="nav-item">
            <router-link to="/Admin" class="nav-link text-white"
              >Admin</router-link
            >
          </li>
          <li class="nav-item">
            <router-link to="/User" class="nav-link text-white"
              >User</router-link
            >
          </li>
        </ul>
      </div>
    </nav>
    <div>
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
export default {
  name: "App"
};
</script>

<style></style>
