// Angular_React_Vue/Day3/Assignments/Vue/Source/databinding/src/App.vue
<template>
  <div>
    <RectangleArea></RectangleArea>
    <LoginComponent></LoginComponent>
    <SignUp></SignUp>
  </div>
</template>

<script>
import RectangleArea from './components/Rectangle.vue'
import LoginComponent from './components/Login.vue'
import SignUp from './components/SignUp.vue'

export default {
  name: 'App',
  components: {
    RectangleArea,
    LoginComponent,
    SignUp
  }
}
</script>

<style></style>

// React/Day 3/Assignments/Data Binding/Source/data-binding/src/App.js
import './App.css';
import RectangleArea from './Rectangle';
import UserLogin from './Login';
import SignUp from './Signup';

function App() {
  return (
    <div className="App">
       <RectangleArea></RectangleArea>
       <UserLogin></UserLogin>
       <SignUp></SignUp>
    </div>
  );
}

export default App;
