// Vue/Day 7/Practice/Child to Parent/Source/child-to-parent/src/components/ProfileComponent.vue
<template lang="en">
    <div>
        <h1 class="my-3 text-center display-6 text-primary">Passing value from Child to Parent Component</h1>
        <div class="text-center">
            <form>
                <label for="Name" class="form-label fs-5">Enter your Name: </label>
                <input type="text" v-model="Name" name="Name" id="Name" class="mx-2 mb-3 form-control-sm text-primary" /><br />
                <button type="button" @click="passData()" class="btn btn-outline-primary ms-0 mx-2">Send Data</button>
            </form>
        </div> 
    </div>
</template>
<script>
export default {
    name: 'ProfileComponent',
    data() {
        return {
            Name: ""
        }
    },
    methods: {
        passData() {
            this.$emit("getValue", this.Name);
        }
    },
}
</script>
<style scoped></style>

// Angular/Day 7/Practice/Child to Parent/Source/child-to-parent/src/app/profile/profile.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';


@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {

  Name: string = "";

  @Output() getValue = new EventEmitter<any>();

  constructor() { }

  ngOnInit(): void {
  }

  passData() {
    this.getValue.emit(this.Name);
  }
  
}

<h1 class="my-3 text-center display-6 text-primary">Passing value from Child to Parent Component</h1>
<div class="text-center">
    <form>
        <label for="Name" class="form-label fs-5">Enter your Name: </label>
        <input type="text" [(ngModel)]="Name" name="Name" id="Name" class="mx-2 mb-3 form-control-sm text-primary" /><br />
        <button (click)="passData()" class="btn btn-outline-primary ms-0 mx-2">Click me</button>
    </form>
</div>
