// Angular_React_Vue/Day3/Assignments/Vue/Source/databinding/src/components/Login.vue
<template lang="en">
    <div>
        <h1 class="display-5 text-primary text-center">Login with Validation</h1>
        <div class="container mx-auto mt-2">
            <form action="">
                <label for="username" class="form-label fs-5">Username: </label>
                <input type="text" v-model="username" name="username" id="username" class="form-control-sm mx-2 text-primary mb-3" /><br />
                <label for="password" class="form-label fs-5">Password:</label>
                <input type="password" v-model="password" name="password" id="password" class="form-control-sm mx-2 text-primary mb-4" /><br />
                <button type="button" @click="validate" class="btn btn-outline-primary ms-0 mx-2">Login</button>
                <button @click="clear" class="btn btn-outline-primary">Clear</button>
            </form>
            <h3 class="display-6 mt-3 mb-3 fs-3">Status: {{ result }}</h3>
        </div>
    </div>
</template>
<script>
export default {
    name: 'LoginComponent',
    data() {
        return {
            username: "",
            password: "",
            result: "" 
        }
    },
    methods: {
        validate() {
            if(this.username == "admin" && this.password == "admin"){
            this.result = "Valid User";
            }
            else{
            this.result = "Invalid User";
            }
        },

        clear() {
            this.username = "";
            this.password = "";
            this.result = "";
        }
    },
}
</script>
<style scoped></style>

// Angular_React_Vue/Day16/Assignments/React/Source/access-control/src/routes/Login.js
import React from "react";
import { useState } from "react";

export default function Login() {
  const [userName, setuserName] = useState("");
  const [pwd, setpwd] = useState("");

  const userLogin = () => {
      if((userName === "admin" && pwd === "admin") || (userName === "user" && pwd === "user")) {
        localStorage.setItem("user", userName);
      }
  };

  const userLogout = () => {
    return localStorage.removeItem("user");
  };

  return (
    <div className="text-center pt-2 pb-4 bg-light">
      <h1 className="display-5 text-primary">Login with Validation</h1>
      <div className="container mx-auto mt-4">
        <form action="">
          <label for="username" className="form-label fs-5">
            Username:{" "}
          </label>
          <input
            type="text"
            onChange={(e) => setuserName(e.target.value)}
            name="username"
            id="username"
            className="form-control-sm mx-2 text-primary mb-3"
          />
          <br />
          <label for="password" className="form-label fs-5">
            Password:
          </label>
          <input
            type="password"
            onChange={(e) => setpwd(e.target.value)}
            name="password"
            id="password"
            className="form-control-sm mx-2 text-primary mb-4"
          />
          <br />
          <button
            type="button"
            onClick={userLogin}
            className="btn btn-outline-primary ml-0 mx-2"
          >
            Login
          </button>
          <button
            type="button"
            onClick={userLogout}
            className="btn btn-outline-primary"
          >
            Logout
          </button>
        </form>
      </div>
    </div>
  );
}
