// Angular_React_Vue/Day17/Assignments/Angular/Source/http-posts/src/app/post-list/post-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { HttppostsService } from '../httpposts.service';
import { Post } from '../Models/PostModel';

@Component({
  selector: 'app-post-list',
  templateUrl: './post-list.component.html',
  styleUrls: ['./post-list.component.css']
})
export class PostListComponent implements OnInit {

  @Input() postForm!: FormGroup;
  posts: Array<Post> = [];
  deletedPost!: any;

  constructor(private httpPostsService: HttppostsService) { }

  ngOnInit(): void {
    this.httpPostsService.getPosts().subscribe((i: Post[]) => {
      this.posts = i;
    });
  }

  updatePost(updatedPost: Post) {
    this.postForm.setValue(updatedPost);
  }

  deletePost(id: number) {
    this.httpPostsService.deletePosts(id).subscribe((i) => {
      this.deletedPost = i;
      console.log(this.deletedPost);
    })
  }

}

<h1 class="my-3 text-center display-4">Posts</h1>
<div class="container">
  <div class="row">
    <div class="col-4 mb-3" *ngFor="let post of posts">
      <div class="card m-2" style="width: 400px">
        <div class="card-header text-center display-6 text-primary fs-2">
          Post ID: {{ post.id }}
        </div>
        <div class="card-body">
          <p class="card-text text-secondary display-6 fs-3">
            <em>User ID: {{ post.user_id }}</em>
          </p>
          <h4 class="card-title">{{ post.title }}</h4>
          <p class="card-text">{{ post.body }}</p>
        </div>
        <div class="card-footer text-center">
          <button class="btn btn-primary mx-2" (click)="updatePost(post)">Edit Post</button>
          <button class="btn btn-primary mx-2" (click)="deletePost(post.id)">Delete Post</button>
        </div>
      </div>
    </div>
  </div>
</div>

// Angular_React_Vue/Day18/Assignments/Vue/Source/http-posts/src/components/PostList.vue
<template lang="en">
  <div>
    <h1 class="my-3 text-center display-4">Posts</h1>
    <div class="container">
      <div class="row">
        <div class="col-4 mb-3" v-for="(post, index) in posts" :key="index">
          <div class="card m-2" style="width: 400px">
            <div class="card-header text-center display-6 text-primary fs-2">
              Post ID: {{ post.id }}
            </div>
            <div class="card-body">
              <p class="card-text text-secondary display-6 fs-3">
                <em>User ID: {{ post.user_id }}</em>
              </p>
              <h4 class="card-title">{{ post.title }}</h4>
              <p class="card-text">{{ post.body }}</p>
            </div>
            <div class="card-footer text-center">
              <button class="btn btn-primary mx-2" @click="updatePost(post, post.id)" >Edit Post</button>
              <button class="btn btn-primary mx-2" @click="deletePost(post.id)">Delete Post</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: "PostList",
  data() {
    return {
      url: "https://gorest.co.in/public/v2/",
      accessToken: "cb434a80c95f5e8698c50cae96f8cb4c7b5da617356b72d58c96a28d7407eb99"
    }
  },
  props: {
    posts: Array
  },
  methods: {
    updatePost(postData, postID) {
      this.$emit("selectedPost", postData);
      this.$emit("selectedId",postID);
    },
    async deletePost(postId) {
      let getUpdatedData = await axios.delete(`${this.url}posts/${postId}`, {headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${this.accessToken}`
        }
      });
      console.log(getUpdatedData.data);
    },
  },
};
</script>
<style scoped></style>
